# Generated by Django 3.0.7 on 2020-06-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
